In [8]:
import numpy as np

In [9]:
arr=np.array([34,45,66,78])

In [10]:
arr

array([34, 45, 66, 78])

In [11]:
print(arr)

[34 45 66 78]


In [12]:
np.__version__

'1.26.4'

In [13]:
arr.sum()

223

In [14]:
arr.dtype

dtype('int32')

# dimensions in numpy array

In [15]:
a=np.array(45)

In [16]:
b = np.array((34, 45), ndmin=5)

In [17]:
c=np.array(((34,56),(45,23)))

In [18]:
d=np.array((((45,56),(4,23)),((40,40),(89,90))))

In [19]:
d

array([[[45, 56],
        [ 4, 23]],

       [[40, 40],
        [89, 90]]])

In [20]:
a.ndim

0

In [21]:
b.ndim

1

In [22]:
c.ndim

2

In [23]:
d.ndim

3

## Array Indexing in Numpy

In [20]:
d[0][0]

array([45, 56])

In [21]:
d[0][0][0]

45

In [27]:
z=np.array([[23,34,56,78,26,78,90],[44,55,66,77,88,99,11]])

In [28]:
z

array([[23, 34, 56, 78, 26, 78, 90],
       [44, 55, 66, 77, 88, 99, 11]])

In [24]:
z[4]

26

In [29]:
z[1,1]

55

In [31]:
z[0,0]

23

In [32]:
z[0,1:3]

array([34, 56])

In [33]:
y=np.array([34,55,66,34,556,78,99])

In [34]:
y

array([ 34,  55,  66,  34, 556,  78,  99])

In [35]:
y[0]

34

In [36]:
y[1:5]

array([ 55,  66,  34, 556])

In [37]:
y[1:5]

array([ 55,  66,  34, 556])

In [38]:
y[1:6:3]

array([ 55, 556])

## Data Types in Numpy

In [39]:
y.dtype

dtype('int32')

In [40]:
x=np.array([23,44,56,78,90,25,76,98])

In [41]:
x

array([23, 44, 56, 78, 90, 25, 76, 98])

In [42]:
x.dtype

dtype('int32')

In [43]:
complex_array = np.array([1 + 2j, 3 + 4j, 5 + 6j])

In [44]:
complex_array

array([1.+2.j, 3.+4.j, 5.+6.j])

In [45]:
ca = np.array([1, 2, 3], dtype=complex)

In [46]:
ca

array([1.+0.j, 2.+0.j, 3.+0.j])

In [47]:
ca.dtype

dtype('complex128')

In [52]:
u = np.array([1+2j, 4+1j])

In [62]:
k=np.array([34.2,33.33, 45.53,222334],dtype='S')

In [63]:
k

array([b'34.2', b'33.33', b'45.53', b'222334'], dtype='|S6')

In [59]:
k.dtype

dtype('S8')

In [64]:
##copy

te=x.copy()

In [65]:
te

array([23, 44, 56, 78, 90, 25, 76, 98])

In [66]:
## shape

x.shape

(8,)

In [67]:
z=np.array(([34,33,45,67,23,45,68]))